[package]
name = "hashmash"
version = "0.1.0"
authors = ["Sven Steinbauer <sven@themill.com>"]

[dependencies]
rust-crypto = "^0.2"
clap = "~2.23.2"
rayon = "~0.7.0"
permutohedron = "~0.2.2"
time = "0.1"